---
# Certificate tasks file for ansible-role-apache-settings

- name: "Get SSLCertificateFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateFile" {{ ssl_config }} | grep -v "#" | sed -e 's/^\s*//' | tr '\t' ' '
  register: output
  changed_when: output.rc != 0

- name: "Set facts based on SSLCertificateFile output"
  ansible.builtin.set_fact:
    ssl_certificate: "{{ output.stdout }}"
    ssl_certificate_file: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[1] }}"
    ssl_certificate_path: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[0] }}"

- name: "Get SSLCertificateKeyFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateKeyFile" {{ ssl_config }} | grep -v "#" | sed -e 's/^\s*//' | tr '\t' ' '
  register: output
  changed_when: output.rc != 0

- name: "Set facts based on SSLCertificateKeyFile output"
  ansible.builtin.set_fact:
    ssl_key: "{{ output.stdout }}"
    ssl_key_file: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[1] }}"
    ssl_key_path: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[0] }}"

- name: "Get SSLCertificateChainFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateChainFile" {{ ssl_config }} | grep -v "#" | sed -e 's/^\s*//' | tr '\t' ' '
  register: output
  changed_when: output.rc != 0

- name: "Set facts based on SSLCertificateChainFile output"
  ansible.builtin.set_fact:
    ssl_chain: "{{ output.stdout }}"
    ssl_chain_file: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[1] }}"
    ssl_chain_path: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[0] }}"

- name: "Upload Certificates to {{ inventory_hostname }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0640'
  with_items:
    - {
        src: "{{ certificate_file }}",
        dest: "{{ ssl_certificate_path }}/"
      }
    - {
        src: "{{ certificate_key }}",
        dest: "{{ ssl_key_path }}/"
      }
    - {
        src: "{{ certificate_chain }}",
        dest: "{{ ssl_chain_path }}/"
      }

- name: "Update {{ ssl_config }} with new Certificate file"
  ansible.builtin.lineinfile:
    dest: "{{ ssl_config }}"
    regexp: '^\s*SSLCertificateFile(\s+)(\S*)$'
    line: "SSLCertificateFile {{ ssl_certificate_path }}/{{ certificate_file.rsplit('/', 1)[1] }}"
    state: present
    #validate: 'apachectl -t'
    mode: '0640'

- name: "Update {{ ssl_config }} with new Certificate Key"
  ansible.builtin.lineinfile:
    dest: "{{ ssl_config }}"
    regexp: '^\s*SSLCertificateKeyFile(\s+)(\S*)$'
    line: "SSLCertificateKeyFile {{ ssl_key_path }}/{{ certificate_key.rsplit('/', 1)[1] }}"
    state: present
    #validate: 'apachectl -t'
    mode: '0640'

- name: "Update {{ ssl_config }} with new CA Certificate file bundle"
  ansible.builtin.lineinfile:
    dest: "{{ ssl_config }}"
    regexp: '^\s*SSLCertificateChainFile(\s+)(\S*)$'
    line: "SSLCertificateChainFile {{ ssl_chain_path }}/{{ certificate_chain.rsplit('/', 1)[1] }}"
    state: present
    #validate: 'apachectl -t'
    mode: '0640'
  notify: "Restart Apache HTTP Server Daemon"
