---
# Debian tasks file for ansible-role-apache-settings

- name: "Collect list of enabled site configurations"
  ansible.builtin.shell:
    cmd: "ls {{ apache_dir }}/sites-enabled/"
  register: sites

- name: "Debug"
  debug:
    var: sites

- name: "Include tasks from cert playbook"
  ansible.builtin.include_tasks: "tasks/Redhat.yaml"
  vars:
      ssl_config: "{{ item }}"
  with_items:
    - sites
