---
# Debian tasks file for ansible-role-apache-settings

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Include tasks from cert playbook"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yaml"
