---
# tasks file for ansible-role-apache-settings

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Get SSLCertificateFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateFile /" {{ ssl_config }} | grep -v "#"
  register: sslcertificatefile

- name: Print returned information
  ansible.builtin.debug:
    msg: "{{ sslcertificatefile.stdout.split(' ') }}"
