---
# tasks file for ansible-role-apache-settings

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Get path"
  ansible.builtin.slurp:
    src: "{{ ssl_config }}"
  register: lines

- name: Print returned information
  ansible.builtin.debug:
    msg: "{{ lines['content'] | b64decode }}"