---
# tasks file for ansible-role-apache-settings

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Get SSLCertificateFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateFile /" {{ ssl_config }} | grep -v "#"
  register: output

- name: "Set fact for file"
  ansible.builtin.set_fact:
    ssl_certificate_file: "{{ output.stdout.split(' ')[1].split('/', 1)[1] }}"

- name: Print returned information
  ansible.builtin.debug:
    var: ssl_certificate_file
    #msg: "{{ sslcertificatefile.stdout.split(' ') }}"
