---
# tasks file for ansible-role-apache-settings

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Get SSLCertificateFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateFile /" {{ ssl_config }} | grep -v "#"
  register: output

- name: "Set facts based on SSLCertificateFile output"
  ansible.builtin.set_fact:
    ssl_certificate_file: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[1] }}"
    ssl_certificate_path: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[0] }}"

- name: "Get SSLCertificateKeyFile path from {{ ssl_config }}"
  ansible.builtin.shell:
    cmd: grep -i "SSLCertificateKeyFile /" {{ ssl_config }} | grep -v "#"
  register: output

- name: "Set facts based on SSLCertificateKeyFile output"
  ansible.builtin.set_fact:
    ssl_key_file: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[1] }}"
    ssl_key_path: "{{ output.stdout.split(' ')[1].rsplit('/', 1)[0] }}"

- name: Print returned information
  ansible.builtin.debug:
    var: ssl_key_file
    #msg: "{{ sslcertificatefile.stdout.split(' ') }}"
